/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillRouteImport } from './routes/skill'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContributingRouteImport } from './routes/contributing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs.troubleshooting'
import { Route as DocsToolsRouteImport } from './routes/docs.tools'
import { Route as DocsReleaseGuideRouteImport } from './routes/docs.release-guide'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsMcreatorSkillRouteImport } from './routes/docs.mcreator-skill'
import { Route as DocsMcpClientsRouteImport } from './routes/docs.mcp-clients'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsGeckolibRouteImport } from './routes/docs.geckolib'
import { Route as DocsChangelogRouteImport } from './routes/docs.changelog'
import { Route as DocsArchitectureRouteImport } from './routes/docs.architecture'

const SkillRoute = SkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributingRoute = ContributingRouteImport.update({
  id: '/contributing',
  path: '/contributing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsToolsRoute = DocsToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReleaseGuideRoute = DocsReleaseGuideRouteImport.update({
  id: '/release-guide',
  path: '/release-guide',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMcreatorSkillRoute = DocsMcreatorSkillRouteImport.update({
  id: '/mcreator-skill',
  path: '/mcreator-skill',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMcpClientsRoute = DocsMcpClientsRouteImport.update({
  id: '/mcp-clients',
  path: '/mcp-clients',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGeckolibRoute = DocsGeckolibRouteImport.update({
  id: '/geckolib',
  path: '/geckolib',
  getParentRoute: () => DocsRoute,
} as any)
const DocsChangelogRoute = DocsChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contributing': typeof ContributingRoute
  '/docs': typeof DocsRouteWithChildren
  '/skill': typeof SkillRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/geckolib': typeof DocsGeckolibRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/mcp-clients': typeof DocsMcpClientsRoute
  '/docs/mcreator-skill': typeof DocsMcreatorSkillRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/release-guide': typeof DocsReleaseGuideRoute
  '/docs/tools': typeof DocsToolsRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contributing': typeof ContributingRoute
  '/skill': typeof SkillRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/geckolib': typeof DocsGeckolibRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/mcp-clients': typeof DocsMcpClientsRoute
  '/docs/mcreator-skill': typeof DocsMcreatorSkillRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/release-guide': typeof DocsReleaseGuideRoute
  '/docs/tools': typeof DocsToolsRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contributing': typeof ContributingRoute
  '/docs': typeof DocsRouteWithChildren
  '/skill': typeof SkillRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/geckolib': typeof DocsGeckolibRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/mcp-clients': typeof DocsMcpClientsRoute
  '/docs/mcreator-skill': typeof DocsMcreatorSkillRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/release-guide': typeof DocsReleaseGuideRoute
  '/docs/tools': typeof DocsToolsRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contributing'
    | '/docs'
    | '/skill'
    | '/docs/architecture'
    | '/docs/changelog'
    | '/docs/geckolib'
    | '/docs/installation'
    | '/docs/mcp-clients'
    | '/docs/mcreator-skill'
    | '/docs/quickstart'
    | '/docs/release-guide'
    | '/docs/tools'
    | '/docs/troubleshooting'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contributing'
    | '/skill'
    | '/docs/architecture'
    | '/docs/changelog'
    | '/docs/geckolib'
    | '/docs/installation'
    | '/docs/mcp-clients'
    | '/docs/mcreator-skill'
    | '/docs/quickstart'
    | '/docs/release-guide'
    | '/docs/tools'
    | '/docs/troubleshooting'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contributing'
    | '/docs'
    | '/skill'
    | '/docs/architecture'
    | '/docs/changelog'
    | '/docs/geckolib'
    | '/docs/installation'
    | '/docs/mcp-clients'
    | '/docs/mcreator-skill'
    | '/docs/quickstart'
    | '/docs/release-guide'
    | '/docs/tools'
    | '/docs/troubleshooting'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContributingRoute: typeof ContributingRoute
  DocsRoute: typeof DocsRouteWithChildren
  SkillRoute: typeof SkillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skill': {
      id: '/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof SkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributing': {
      id: '/contributing'
      path: '/contributing'
      fullPath: '/contributing'
      preLoaderRoute: typeof ContributingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tools': {
      id: '/docs/tools'
      path: '/tools'
      fullPath: '/docs/tools'
      preLoaderRoute: typeof DocsToolsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/release-guide': {
      id: '/docs/release-guide'
      path: '/release-guide'
      fullPath: '/docs/release-guide'
      preLoaderRoute: typeof DocsReleaseGuideRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/mcreator-skill': {
      id: '/docs/mcreator-skill'
      path: '/mcreator-skill'
      fullPath: '/docs/mcreator-skill'
      preLoaderRoute: typeof DocsMcreatorSkillRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/mcp-clients': {
      id: '/docs/mcp-clients'
      path: '/mcp-clients'
      fullPath: '/docs/mcp-clients'
      preLoaderRoute: typeof DocsMcpClientsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/geckolib': {
      id: '/docs/geckolib'
      path: '/geckolib'
      fullPath: '/docs/geckolib'
      preLoaderRoute: typeof DocsGeckolibRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/changelog': {
      id: '/docs/changelog'
      path: '/changelog'
      fullPath: '/docs/changelog'
      preLoaderRoute: typeof DocsChangelogRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsChangelogRoute: typeof DocsChangelogRoute
  DocsGeckolibRoute: typeof DocsGeckolibRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsMcpClientsRoute: typeof DocsMcpClientsRoute
  DocsMcreatorSkillRoute: typeof DocsMcreatorSkillRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsReleaseGuideRoute: typeof DocsReleaseGuideRoute
  DocsToolsRoute: typeof DocsToolsRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsChangelogRoute: DocsChangelogRoute,
  DocsGeckolibRoute: DocsGeckolibRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsMcpClientsRoute: DocsMcpClientsRoute,
  DocsMcreatorSkillRoute: DocsMcreatorSkillRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsReleaseGuideRoute: DocsReleaseGuideRoute,
  DocsToolsRoute: DocsToolsRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContributingRoute: ContributingRoute,
  DocsRoute: DocsRouteWithChildren,
  SkillRoute: SkillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
